esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:

improv_serial:

packages:
  ld2450: !include common/ld2450.yaml